// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXtM7vUppLjsIQblBYJ6ko3vRZmOcFLSQ',
    appId: '1:92634320339:web:99e3a6d08cfa3bd6bff326',
    messagingSenderId: '92634320339',
    projectId: 'application-13302',
    authDomain: 'application-13302.firebaseapp.com',
    databaseURL: 'https://application-13302-default-rtdb.firebaseio.com',
    storageBucket: 'application-13302.appspot.com',
    measurementId: 'G-K51DW2P320',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPGJFbcrGDkVXuT_6FJg9uqkcnnhivtu8',
    appId: '1:92634320339:android:25b3c2ddf32e337abff326',
    messagingSenderId: '92634320339',
    projectId: 'application-13302',
    databaseURL: 'https://application-13302-default-rtdb.firebaseio.com',
    storageBucket: 'application-13302.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQTJxKQhhNgrWNJB3aBcKXrP5W-N4BcA',
    appId: '1:92634320339:ios:aa98d0e744434e0abff326',
    messagingSenderId: '92634320339',
    projectId: 'application-13302',
    databaseURL: 'https://application-13302-default-rtdb.firebaseio.com',
    storageBucket: 'application-13302.appspot.com',
    iosBundleId: 'com.example.ctintegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQTJxKQhhNgrWNJB3aBcKXrP5W-N4BcA',
    appId: '1:92634320339:ios:aa98d0e744434e0abff326',
    messagingSenderId: '92634320339',
    projectId: 'application-13302',
    databaseURL: 'https://application-13302-default-rtdb.firebaseio.com',
    storageBucket: 'application-13302.appspot.com',
    iosBundleId: 'com.example.ctintegration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpLl6MuxxcSJfiA65CxE9JnzUD6yiAGGY',
    appId: '1:92634320339:web:a89a4bd581c8d16cbff326',
    messagingSenderId: '92634320339',
    projectId: 'application-13302',
    authDomain: 'application-13302.firebaseapp.com',
    databaseURL: 'https://application-13302-default-rtdb.firebaseio.com',
    storageBucket: 'application-13302.appspot.com',
    measurementId: 'G-FHV9073EL6',
  );
}
